### ISSUE TITLE
stream_compressor.cc  error: no matching member function for call to 'NewInstance'

### ISSUE THREAD

**Issue by patrickkh7788** [zwb-ict/node-zstd#1]
../src/compress/stream_compressor.cc:95:39: error: no matching member function for call to 'NewInstance'
      info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                ~~~~~~^~~~~~~~~~~
/var/root/.node-gyp/10.10.0/include/node/v8.h:3992:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/var/root/.node-gyp/10.10.0/include/node/v8.h:3989:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
1 error generated.
make: *** [Release/obj.target/nzcompressor/src/compress/stream_compressor.o] Error 1

**Comment by josephrocca** [comment]
Was this solved? I'm getting something similar on Ubuntu 16.04, Node 10.9.0
```
npm i node-fetch node-zstd

> node-zstd@2.0.1 install /home/joe/Desktop/keep/code/SCRAP/zstd-memory-spike/node_modules/node-zstd
> node-gyp rebuild

make: Entering directory '/home/joe/Desktop/keep/code/SCRAP/zstd-memory-spike/node_modules/node-zstd/build'
  CC(target) Release/obj.target/compressor/deps/zstd/lib/common/entropy_common.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/common/fse_decompress.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/common/xxhash.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/common/zstd_common.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/compress/fse_compress.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/compress/huf_compress.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/compress/zbuff_compress.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/compress/zstd_compress.o
  AR(target) Release/obj.target/deps/compressor.a
  COPY Release/compressor.a
  CXX(target) Release/obj.target/compressor/src/common/stream_coder.o
  CXX(target) Release/obj.target/compressor/src/common/allocator.o
  CXX(target) Release/obj.target/compressor/src/compress/compressor_index.o
  CXX(target) Release/obj.target/compressor/src/compress/stream_compressor.o
../src/compress/stream_compressor.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ZSTD_NODE::StreamCompressor::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/compress/stream_compressor.cc:95:61: error: no matching function for call to ‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [1])’
       info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                             ^
In file included from /home/joe/.node-gyp/10.9.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:53,
                 from ../src/compress/stream_compressor.h:4,
                 from ../src/compress/stream_compressor.cc:1:
/home/joe/.node-gyp/10.9.0/include/node/v8.h:3976:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/joe/.node-gyp/10.9.0/include/node/v8.h:3976:44: note:   candidate expects 3 arguments, 2 provided
/home/joe/.node-gyp/10.9.0/include/node/v8.h:3979:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/joe/.node-gyp/10.9.0/include/node/v8.h:3979:44: note:   candidate expects 1 argument, 2 provided
compressor.target.mk:114: recipe for target 'Release/obj.target/compressor/src/compress/stream_compressor.o' failed
make: *** [Release/obj.target/compressor/src/compress/stream_compressor.o] Error 1
make: Leaving directory '/home/joe/Desktop/keep/code/SCRAP/zstd-memory-spike/node_modules/node-zstd/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/joe/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.4.0-141-generic
gyp ERR! command "/home/joe/.nvm/versions/node/v10.9.0/bin/node" "/home/joe/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/joe/Desktop/keep/code/SCRAP/zstd-memory-spike/node_modules/node-zstd
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN zstd-memory-spike@1.0.0 No description
npm WARN zstd-memory-spike@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-zstd@2.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-zstd@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Similar to [this issue](https://github.com/tugrul/node-mcrypt/issues/72#issuecomment-411343906) on `node-mcrypt`?

**Comment by rodolfoleal** [comment]
Try

npm i node-fetch node-zstd --ignore-scripts
