### ISSUE TITLE
node-zstd npm installation fails on nodejs version 10.16.0

### ISSUE THREAD

**Issue by Dhvani-Katkoria** [zwb-ict/node-zstd#4]
Unable to install node-zstd module for nodejs version 10.16.0. 

Npm version: 6.9.0
Node-zstd version: 2.0.1 (latest version)

How to compile node-zstd on nodejs version 10.16.0?

Complete log : 

`$ npm install node-zstd

> node-zstd@2.0.1 install /home/dhvani/Npm_modules_test/node_modules/node-zstd
> node-gyp rebuild

make: Entering directory '/home/dhvani/Npm_modules_test/node_modules/node-zstd/build'
  CC(target) Release/obj.target/compressor/deps/zstd/lib/common/entropy_common.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/common/fse_decompress.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/common/xxhash.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/common/zstd_common.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/compress/fse_compress.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/compress/huf_compress.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/compress/zbuff_compress.o
  CC(target) Release/obj.target/compressor/deps/zstd/lib/compress/zstd_compress.o
  AR(target) Release/obj.target/deps/compressor.a
  COPY Release/compressor.a
  CXX(target) Release/obj.target/compressor/src/common/stream_coder.o
  CXX(target) Release/obj.target/compressor/src/common/allocator.o
  CXX(target) Release/obj.target/compressor/src/compress/compressor_index.o
  CXX(target) Release/obj.target/compressor/src/compress/stream_compressor.o
../src/compress/stream_compressor.cc: In constructor ‘ZSTD_NODE::StreamCompressor::StreamCompressor(v8::Local<v8::Object>)’:
../src/compress/stream_compressor.cc:50:65: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated (declared at /home/dhvani/.node-gyp/10.16.0/include/node/v8.h:2478): Use maybe version [-Wdeprecated-declarations]
       level = Get(userParams, key).ToLocalChecked()->Int32Value();
                                                                 ^
../src/compress/stream_compressor.cc:54:79: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/dhvani/.node-gyp/10.16.0/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
       Local<Object> dictBuf = Get(userParams, key).ToLocalChecked()->ToObject();
                                                                               ^
../src/compress/stream_compressor.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ZSTD_NODE::StreamCompressor::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/compress/stream_compressor.cc:86:69: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/dhvani/.node-gyp/10.16.0/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
       StreamCompressor *sc = new StreamCompressor(info[0]->ToObject());
                                                                     ^
../src/compress/stream_compressor.cc:95:61: error: no matching function for call to ‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [1])’
       info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                             ^
../src/compress/stream_compressor.cc:95:61: note: candidates are:
In file included from /home/dhvani/.node-gyp/10.16.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/compress/stream_compressor.h:4,
                 from ../src/compress/stream_compressor.cc:1:
/home/dhvani/.node-gyp/10.16.0/include/node/v8.h:3993:44: note: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/dhvani/.node-gyp/10.16.0/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 2 provided
/home/dhvani/.node-gyp/10.16.0/include/node/v8.h:3996:44: note: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/dhvani/.node-gyp/10.16.0/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 2 provided
../src/compress/stream_compressor.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ZSTD_NODE::StreamCompressor::Copy(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/compress/stream_compressor.cc:105:48: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/dhvani/.node-gyp/10.16.0/include/node/v8.h:10046): Use maybe version [-Wdeprecated-declarations]
     Local<Object> chunkBuf = info[0]->ToObject();
                                                ^
compressor.target.mk:114: recipe for target 'Release/obj.target/compressor/src/compress/stream_compressor.o' failed
make: *** [Release/obj.target/compressor/src/compress/stream_compressor.o] Error 1
make: Leaving directory '/home/dhvani/Npm_modules_test/node_modules/node-zstd/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dhvani/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/home/dhvani/.nvm/versions/node/v10.16.0/bin/node" "/home/dhvani/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dhvani/Npm_modules_test/node_modules/node-zstd
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN npmtest@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-zstd@2.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-zstd@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by xamgore** [comment]
Same with node `v14.13.0`.

**Comment by renanwilliam** [comment]
Same with node v12.19.0

**Comment by dvtate** [comment]
same with v16.4.2

**Comment by andrewwiik** [comment]
Has anyone found a solution?

**Comment by dvtate** [comment]
don't use this library, or anything based on it

**Comment by renanwilliam** [comment]
Unfortunately I give up too. I'm changed to [zstd-codec](https://github.com/yoshihitoh/zstd-codec) and it working very well
